service: soccer
frameworkVersion: "2"

package:
  include:
    - src
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  region: ap-northeast-2
  environment:
    NODE_ENV: development

functions:
  certificateUser:
    handler: src/user.certificateUser
    events:
      - http:
          path: v1/user/auth
          method: get
          request:
            parameters:
              querystrings:
                code: true
  createUser:
    handler: src/user.createUser
    events:
      - http:
          path: v1/user
          method: post
  syncUser:
    handler: src/user.syncUser
    events:
      - http:
          path: v1/sync
          method: get

plugins:
  - serverless-offline
