service: soccer
frameworkVersion: "2"

package:
  include:
    - src
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  region: ap-northeast-2
  environment:
    NODE_ENV: development

functions:
  certificateUser:
    handler: src/user.certificateUser
    events:
      - http:
          path: v1/user/auth
          method: get
          request:
            parameters:
              querystrings:
                code: true
  createUser:
    handler: src/user.createUser
    events:
      - http:
          path: v1/user
          method: post
  syncDB:
    handler: src/sync.syncDB
    events:
      - http:
          path: v1/sync
          method: get
  bbc:
    handler: src/crawling.bbcFootBall
    events:
      - http:
          path: v1/bbc
          method: get
  sky:
    handler: src/crawling.skyFootBall
    events:
      - http:
          path: v1/sky
          method: get
  goal:
    handler: src/crawling.goalFootBall
    events:
      - http:
          path: v1/goal
          method: get

plugins:
  - serverless-offline
