service: soccer
frameworkVersion: "2"

package:
  include:
    - src
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  region: ap-northeast-2
  environment:
    NODE_ENV: development

functions:
  certificateUser:
    handler: src/user.certificateUser
    events:
      - http:
          path: v1/user/auth
          method: get
          request:
            parameters:
              querystrings:
                code: true
  login:
    handler: src/auth.login
    events:
      - http:
          path: v1/auth/login
          method: get
  createUser:
    handler: src/user.createUser
    events:
      - http:
          path: v1/user
          method: post
  syncDB:
    handler: src/sync.syncDB
    events:
      - http:
          path: v1/sync
          method: get
  bbc:
    handler: src/crawling.bbcFootBall
    events:
      - http:
          path: v1/bbc
          method: get
  sky:
    handler: src/crawling.skyFootBall
    events:
      - http:
          path: v1/sky
          method: get
  goal:
    handler: src/crawling.goalFootBall
    events:
      - http:
          path: v1/goal
          method: get
  getNews:
    handler: src/news.get
    events:
      - http:
          path: v1/news/{newsId}
          method: get
          request:
            parameters:
              paths:
                newsId: true
  getRecentNews:
    handler: src/news.getRecentNews
    events:
      - http:
          path: v1/news/recent
          method: get
  getNewsList:
    handler: src/news.getNewsList
    events:
      - http:
          path: v1/news
          method: get
          request:
            parameters:
              querystrings:
                page: false
  getNewsCnt:
    handler: src/news.newsAllCount
    events:
      - http:
          path: v1/news/cnt
          method: get
  getReply:
    handler: src/news.getReply
    events:
      - http:
          path: v1/news/{newsId}/reply
          method: get
          request:
            parameters:
              paths:
                newsId: true

plugins:
  - serverless-offline
